import DoubleMonumentsList from "@/components/product/DoubleMonumentsList";

export const metadata = {
  title: "Подвійні пам`ятники",
  description: "Generated by create next app",
};

const DoubleMonuments = () => {
  return <DoubleMonumentsList />;
};

export default DoubleMonuments;
