import AdminSingleProduct from "@/components/admin/AdminSingleProduct";
import PrivateRoute from "@/components/admin/PrivateRoute";

export const metadata = {
  title: "Одинарні пам`ятники",
  description: "Generated by create next app",
};
const AdminSingle = () => {
  return (
    <>
      <PrivateRoute>
        <AdminSingleProduct />
      </PrivateRoute>
    </>
  );
};

export default AdminSingle;
