import AboutUs from "@/components/AboutUs";

export const metadata = {
  title: "Про нас",
  description: "Generated by create next app",
};

const About = () => {
  return <AboutUs />;
};
export default About;
