import IconsList from "@/components/product/IconsList";

export const metadata = {
  title: "Ікони до пам`ятника",
  description: "Generated by create next app",
};

const Icons = () => {
  return <IconsList />;
};

export default Icons;
