import SingleMonumentsList from "@/components/product/SingleMonumentsList";

export const metadata = {
  title: "Одинарні пам`ятники",
  description: "Generated by create next app",
};
const SingleMonuments = () => {
  return <SingleMonumentsList />;
};

export default SingleMonuments;
