import EpitaphsList from "@/components/product/EpitaphsList";

export const metadata = {
  title: "Епітафії до пам`ятника",
  description: "Generated by create next app",
};

const Epitaphs = () => {
  return <EpitaphsList />;
};

export default Epitaphs;
