import AdminIconsProduct from "@/components/admin/AdminIconsProduct";
import PrivateRoute from "@/components/admin/PrivateRoute";

export const metadata = {
  title: "Ікони до пам`ятника",
  description: "Generated by create next app",
};

const adminIcons = () => {
  return (
    <PrivateRoute>
      <AdminIconsProduct />
    </PrivateRoute>
  );
};

export default adminIcons;
