import AdminAccessoriesProduct from "@/components/admin/AdminAccessoriesProduct";
import PrivateRoute from "@/components/admin/PrivateRoute";

export const metadata = {
  title: "Аксесуари до пам`ятника",
  description: "Generated by create next app",
};

const AdminAccessories = () => {
  return (
    <PrivateRoute>
      <AdminAccessoriesProduct />
    </PrivateRoute>
  );
};

export default AdminAccessories;
