import MonumentAccessoriesList from "@/components/product/MonumentAccessoriesList";

export const metadata = {
  title: "Аксесуари до пам`ятника",
  description: "Generated by create next app",
};

const MonumentAccessories = () => {
  return <MonumentAccessoriesList />;
};

export default MonumentAccessories;
