import AdminDoubleMonumentsProduct from "@/components/admin/AdminDoubleMonumentsProduct";
import PrivateRoute from "@/components/admin/PrivateRoute";

export const metadata = {
  title: "Подвійні пам`ятники",
  description: "Generated by create next app",
};

const AdminDoubleMonuments = () => {
  return (
    <PrivateRoute>
      <AdminDoubleMonumentsProduct />
    </PrivateRoute>
  );
};

export default AdminDoubleMonuments;
